### ISSUE TITLE
What specifically should namespaceSelector values be?

### ISSUE THREAD

**Issue by s1rc** [foriequal0/pod-graceful-drain#21]
I'm testing our your chart because the 502 issue on draining is getting out of hand. 

I am trying to restrict with the `namespaceSelector` however none of the values I've tried work. Can you provide an example of what is expected?

Also, thank you for this chart! I'm glad there is something to help. Hoping that better support makes it into AWS Load Balancer itself.

**Comment by foriequal0** [comment]
You might find examples from here: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector

**Comment by s1rc** [comment]
Thank you, I don't know where my head was at.
