### ISSUE TITLE
deprecation of rbac.authorization.k8s.io/v1beta1

### ISSUE THREAD

**Issue by ajaykumarmandapati** [foriequal0/pod-graceful-drain#22]
We would need to upgrade our EKS version to `1.17` from `1.16` which deprecates `rbac.authorization.k8s.io/v1beta1` , we found [relevances](https://github.com/foriequal0/pod-graceful-drain/blob/main/config/rbac/auth_proxy_client_clusterrole.yaml) to it in your code but could not completely understand if they are actively being used in the project.
Could you confirm if these would be upgraded in the near future since we might move to `EKS 1.21` in the coming months.

**Comment by foriequal0** [comment]
The file is generated by `controller-gen`.
I expect it to be naturally migrated to the newer version if I upgrade `controller-gen`.
I also uses EKS so it'll be upgraded someday.

**Comment by ajaykumarmandapati** [comment]
Thanks for your answer, I've raised a PR for the same - https://github.com/foriequal0/pod-graceful-drain/pull/23
