### ISSUE TITLE
Is the helm chart namespace sepecific?

### ISSUE THREAD

**Issue by jyotibhanot** [foriequal0/pod-graceful-drain#38]
If my applications are deployed in test namespace, then this helm chart needs to be deployed in test namespace?

I have deployed in kube-system, will it take care of all the namespaces?

**Comment by foriequal0** [comment]
No, you don't have to. It'll take care of all the namespaces.

**Comment by jyotibhanot** [comment]
Do we need to adjust terminationGracePeriodSeconds or any other value? I am trying to achieve zero downtime deployment using IP as targets as mentioned in the posts 

https://easoncao.com/zero-downtime-deployment-when-using-alb-ingress-controller-on-amazon-eks-and-prevent-502-error/
Do I need to adjust any variable in target group like deregistration delay to make this work?
